version: '3'
services:
  db:
    image: postgres:9.6-alpine

  app:
    build: .
    ports:
      - 8081:8081
    environment:
      - CONTEXT_TIMEOUT=2000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=
      - DB_PORT=
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - PORT=8081
      - VOUCHER_UPLOAD_PATH=./public/images/vouchers/
      - VOUCHER_ROUTE_PATH=public/images/vouchers/
      - VOUCHER_PATH=/images/vouchers
      - JWT_SECRET=docker-compose-secret
      - JWT_TOKEN_EXP=24
      - BASIC_USERNAME=docker-admin
      - BASIC_PASSWORD=docker-admin123