version: '3'
services:
  db:
    image: postgres:9.6-alpine

  app:
    build: .
    ports:
      - 8081:8081
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=
      - DB_PORT=
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - SERVER_PORT=:8081
      - DEBUG_APP=true
      - VOUCHER_UPLOAD_PATH=./public/images/vouchers/
      - VOUCHER_ROUTE_PATH=public/images/vouchers/
      - VOUCHER_PATH=/images/vouchers